(() => {
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),title=document.querySelector('#game-title'),help=document.querySelector('#game-help'),scoreNode=document.querySelector('#score'),message=document.querySelector('#message');
  const game=new URLSearchParams(location.search).get('oyun')||'pacman',names={pacman:['PAC-MAN','Yön tuşlarıyla ilerle, noktaları topla ve hayaletten kaç.'],tetris:['TETRIS','← → hareket · ↑ döndür · ↓ hızlandır · Boşluk: bırak'],mario:['SUPER MARIO','← → koş · ↑ veya Boşluk ile zıpla · Altınları topla.'],invaders:['SPACE INVADERS','← → hareket · Boşluk ile ateş et.']};
  const mode=names[game]?game:'pacman';title.textContent=names[mode][0];help.textContent=names[mode][1];let score=0,ended=false,last=0;const keys=new Set();
  const scoreUpdate=()=>scoreNode.textContent=`SKOR ${String(score).padStart(6,'0')}`;
  const finish=(won,label)=>{if(ended)return;ended=true;message.textContent=won?'TUR TAMAMLANDI!':'OYUN BİTTİ';ctx.fillStyle='#080713dd';ctx.fillRect(0,0,600,480);ctx.fillStyle='#ff3cac';ctx.font='bold 22px monospace';ctx.textAlign='center';ctx.fillText(label,300,230);ctx.fillStyle='white';ctx.font='14px monospace';ctx.fillText('Yeniden başlatmak için Enter',300,265);};
  let update,draw;
  if(mode==='pacman'){
    const map=['###############','#.............#','#.###.###.###.#','#.............#','#.###.#.#.###.#','#.....#.#.....#','###.#.#.#.#.###','#...#.....#...#','#.###.###.###.#','#.............#','###############'].map(r=>r.split(''));
    const p={x:1,y:1,dir:[0,0],want:[0,0]},g={x:13,y:9,dir:[-1,0]};let tick=0;
    const wall=(x,y)=>!map[y]||map[y][x]==='#';
    update=dt=>{tick+=dt;if(tick<115)return;tick=0;if(keys.has('ArrowLeft'))p.want=[-1,0];if(keys.has('ArrowRight'))p.want=[1,0];if(keys.has('ArrowUp'))p.want=[0,-1];if(keys.has('ArrowDown'))p.want=[0,1];if(!wall(p.x+p.want[0],p.y+p.want[1]))p.dir=[...p.want];if(!wall(p.x+p.dir[0],p.y+p.dir[1])){p.x+=p.dir[0];p.y+=p.dir[1];}if(map[p.y][p.x]==='.'){map[p.y][p.x]=' ';score+=10;scoreUpdate();}const ds=[[1,0],[-1,0],[0,1],[0,-1]].filter(([x,y])=>!wall(g.x+x,g.y+y));if(Math.random()<.35||wall(g.x+g.dir[0],g.y+g.dir[1]))g.dir=ds[Math.floor(Math.random()*ds.length)]||[0,0];g.x+=g.dir[0];g.y+=g.dir[1];if(g.x===p.x&&g.y===p.y)finish(false,'HAYALET YAKALADI!');if(!map.some(r=>r.includes('.')))finish(true,'LABİRENT TEMİZ!');};
    draw=()=>{ctx.fillStyle='#080713';ctx.fillRect(0,0,600,480);const s=40,oy=20;map.forEach((r,y)=>r.forEach((c,x)=>{if(c==='#'){ctx.fillStyle='#2620a8';ctx.fillRect(x*s+2,oy+y*s+2,s-4,s-4);ctx.strokeStyle='#40dcff';ctx.strokeRect(x*s+5,oy+y*s+5,s-10,s-10);}else if(c==='.'){ctx.fillStyle='#ffe9a8';ctx.beginPath();ctx.arc(x*s+20,oy+y*s+20,3,0,7);ctx.fill();}}));ctx.fillStyle='#ffe13b';ctx.beginPath();ctx.arc(p.x*s+20,oy+p.y*s+20,15,.25,5.8);ctx.lineTo(p.x*s+20,oy+p.y*s+20);ctx.fill();ctx.fillStyle='#ff4b85';ctx.beginPath();ctx.arc(g.x*s+20,oy+g.y*s+20,15,Math.PI,0);ctx.lineTo(g.x*s+35,oy+g.y*s+35);ctx.lineTo(g.x*s+20,oy+g.y*s+35);ctx.lineTo(g.x*s+5,oy+g.y*s+35);ctx.fill();ctx.fillStyle='white';ctx.fillRect(g.x*s+12,oy+g.y*s+13,5,7);ctx.fillRect(g.x*s+23,oy+g.y*s+13,5,7);};
  }else if(mode==='tetris'){
    const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];let board,piece,fall=0,speed=520;
    const collides=(x,y,s)=>s.some((r,dy)=>r.some((v,dx)=>v&&(x+dx<0||x+dx>=10||y+dy>=20||(y+dy>=0&&board[y+dy][x+dx]))));const spawn=()=>{piece={shape:shapes[Math.floor(Math.random()*7)].map(r=>r.slice()),x:3,y:0};if(collides(piece.x,piece.y,piece.shape))finish(false,'BLOK TAŞTI!');};const reset=()=>{board=Array.from({length:20},()=>Array(10).fill(0));speed=520;spawn();};reset();
    const move=(dx,dy)=>{if(!collides(piece.x+dx,piece.y+dy,piece.shape)){piece.x+=dx;piece.y+=dy;return true;}if(dy){piece.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)board[piece.y+y][piece.x+x]=1;}));let n=0;board=board.filter(r=>{if(r.every(Boolean)){n++;return false;}return true;});while(board.length<20)board.unshift(Array(10).fill(0));if(n){score+=n*100;speed=Math.max(110,speed-n*18);scoreUpdate();}spawn();}return false;};const rotate=()=>{const s=piece.shape[0].map((_,i)=>piece.shape.map(r=>r[i]).reverse());if(!collides(piece.x,piece.y,s))piece.shape=s;};
    update=dt=>{fall+=dt;if(keys.has('ArrowLeft')){keys.delete('ArrowLeft');move(-1,0);}if(keys.has('ArrowRight')){keys.delete('ArrowRight');move(1,0);}if(keys.has('ArrowUp')){keys.delete('ArrowUp');rotate();}if(keys.has('ArrowDown'))fall+=110;if(keys.has('Space')){keys.delete('Space');while(move(0,1)){};}if(fall>speed){fall=0;move(0,1);}};
    draw=()=>{ctx.fillStyle='#080713';ctx.fillRect(0,0,600,480);const s=22,ox=190,oy=18;ctx.strokeStyle='#242036';for(let y=0;y<=20;y++){ctx.beginPath();ctx.moveTo(ox,oy+y*s);ctx.lineTo(ox+10*s,oy+y*s);ctx.stroke();}for(let x=0;x<=10;x++){ctx.beginPath();ctx.moveTo(ox+x*s,oy);ctx.lineTo(ox+x*s,oy+20*s);ctx.stroke();}board.forEach((r,y)=>r.forEach((v,x)=>{if(v){ctx.fillStyle='#36e7ff';ctx.fillRect(ox+x*s+1,oy+y*s+1,s-2,s-2);}}));piece.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v){ctx.fillStyle='#ff3cac';ctx.fillRect(ox+(piece.x+x)*s+1,oy+(piece.y+y)*s+1,s-2,s-2);}}));};
  }else if(mode==='mario'){
    const world=2200,floor=390,p={x:40,y:330,vx:0,vy:0,w:26,h:34,ground:false},platforms=[{x:0,y:390,w:world,h:90},{x:250,y:310,w:110,h:18},{x:470,y:260,w:130,h:18},{x:720,y:320,w:150,h:18},{x:1010,y:270,w:130,h:18},{x:1280,y:315,w:160,h:18},{x:1610,y:250,w:140,h:18}],coins=Array.from({length:14},(_,i)=>({x:180+i*135,y:300-(i%3)*38,taken:false}));let camera=0;
    update=dt=>{const z=Math.min(dt/16,2);p.vx=(keys.has('ArrowRight')?3.5:0)-(keys.has('ArrowLeft')?3.5:0);if((keys.has('Space')||keys.has('ArrowUp'))&&p.ground){p.vy=-10;p.ground=false;}p.x=Math.max(0,Math.min(world-p.w,p.x+p.vx*z));p.vy+=.48*z;p.y+=p.vy*z;p.ground=false;platforms.forEach(q=>{if(p.vy>=0&&p.x+p.w>q.x&&p.x<q.x+q.w&&p.y+p.h>=q.y&&p.y+p.h-p.vy*z<=q.y){p.y=q.y-p.h;p.vy=0;p.ground=true;}});coins.forEach(c=>{if(!c.taken&&Math.abs(p.x-c.x)<22&&Math.abs(p.y-c.y)<28){c.taken=true;score+=50;scoreUpdate();}});camera=Math.max(0,Math.min(world-600,p.x-220));if(p.y>500)finish(false,'DÜŞTÜN!');if(p.x>world-100)finish(true,'BAYRAĞA ULAŞTIN!');};
    draw=()=>{ctx.fillStyle='#11132d';ctx.fillRect(0,0,600,480);ctx.fillStyle='#201e51';for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(i*115-camera*.2,80+(i%2)*35,48,0,7);ctx.fill();}platforms.forEach(q=>{ctx.fillStyle='#2cbb72';ctx.fillRect(q.x-camera,q.y,q.w,q.h);ctx.fillStyle='#b87333';for(let x=q.x;x<q.x+q.w;x+=30)ctx.fillRect(x-camera,q.y+20,27,12);});coins.forEach(c=>{if(!c.taken){ctx.fillStyle='#ffd632';ctx.beginPath();ctx.arc(c.x-camera,c.y,9,0,7);ctx.fill();}});ctx.fillStyle='#f04444';ctx.fillRect(p.x-camera,p.y,p.w,p.h);ctx.fillStyle='#fff';ctx.fillRect(p.x-camera+16,p.y+7,5,5);ctx.fillStyle='#f4e8c1';ctx.fillRect(world-80-camera,floor-100,4,100);ctx.fillStyle='#ff3cac';ctx.beginPath();ctx.moveTo(world-76-camera,floor-100);ctx.lineTo(world-25-camera,floor-82);ctx.lineTo(world-76-camera,floor-65);ctx.fill();};
  }else{
    let p,shots,enemies,enemyShots,dir=1,enemyTimer=0,fireTimer=0;const reset=()=>{p={x:280,y:425};shots=[];enemyShots=[];enemies=[];for(let y=0;y<4;y++)for(let x=0;x<8;x++)enemies.push({x:65+x*62,y:55+y*42,alive:true});dir=1;};reset();
    update=dt=>{const z=Math.min(dt/16,2);p.x=Math.max(18,Math.min(558,p.x+((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*5*z));fireTimer+=dt;if(keys.has('Space')&&fireTimer>260){shots.push({x:p.x+10,y:p.y});fireTimer=0;}shots.forEach(s=>s.y-=8*z);shots=shots.filter(s=>s.y>0);enemyTimer+=dt;if(enemyTimer>430){enemyTimer=0;let edge=false;enemies.filter(e=>e.alive).forEach(e=>{e.x+=dir*8;if(e.x>560||e.x<20)edge=true;});if(edge){dir*=-1;enemies.forEach(e=>e.y+=14);}const alive=enemies.filter(e=>e.alive);if(alive.length)enemyShots.push({x:alive[Math.floor(Math.random()*alive.length)].x+12,y:alive[0].y+20});}enemyShots.forEach(s=>s.y+=4*z);enemyShots=enemyShots.filter(s=>s.y<480);shots.forEach(s=>enemies.forEach(e=>{if(e.alive&&s.x>e.x-5&&s.x<e.x+27&&s.y>e.y&&s.y<e.y+24){e.alive=false;s.y=-10;score+=10;scoreUpdate();}}));if(enemyShots.some(s=>s.y>p.y-5&&s.y<p.y+25&&Math.abs(s.x-p.x)<18))finish(false,'GEMİ VURULDU!');if(enemies.some(e=>e.alive&&e.y>p.y-28))finish(false,'İSTİLA BAŞARILI!');if(!enemies.some(e=>e.alive))finish(true,'DÜNYA KURTULDU!');};
    draw=()=>{ctx.fillStyle='#080713';ctx.fillRect(0,0,600,480);for(let i=0;i<45;i++){ctx.fillStyle=i%3?'#827fb4':'#36e7ff';ctx.fillRect(i*137%600,i*71%410,2,2);}ctx.fillStyle='#36e7ff';ctx.beginPath();ctx.moveTo(p.x+12,p.y);ctx.lineTo(p.x+27,p.y+32);ctx.lineTo(p.x+12,p.y+26);ctx.lineTo(p.x-3,p.y+32);ctx.fill();enemies.forEach(e=>{if(e.alive){ctx.fillStyle=e.y<100?'#ff3cac':'#8ef06b';ctx.fillRect(e.x,e.y,25,19);ctx.fillStyle='#080713';ctx.fillRect(e.x+5,e.y+6,4,4);ctx.fillRect(e.x+16,e.y+6,4,4);}});ctx.fillStyle='#ffe75b';shots.forEach(s=>ctx.fillRect(s.x,s.y,3,12));ctx.fillStyle='#ff5a54';enemyShots.forEach(s=>ctx.fillRect(s.x,s.y,4,10));};
  }
  function frame(t){const dt=Math.min(t-last||16,40);last=t;if(!ended){update(dt);if(!ended)draw();}requestAnimationFrame(frame);}function restart(){location.reload();}
  document.querySelector('#restart').addEventListener('click',restart);document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='Enter'&&ended){restart();return;}keys.add(e.code==='Space'?'Space':e.key);});document.addEventListener('keyup',e=>keys.delete(e.code==='Space'?'Space':e.key));
  document.querySelectorAll('.touch-pad button').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(k);});['pointerup','pointercancel','pointerleave'].forEach(type=>b.addEventListener(type,()=>keys.delete(k)));});message.textContent='OYUN BAŞLADI';requestAnimationFrame(frame);
})();
